services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      HISTFILE: /usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DEV}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
